title: Mohan Blogs for the World
author: Mohan
email: mohan-the-octocat@github.com
description: > # this means to ignore newlines until "baseurl:"
   Something amazing is about to happen here, so watch!
   
# social links
twitter_username: mohanponders # DO NOT include the @ character, or else the build will fail!
github_username:  mohan-the-octocat # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
